### ISSUE TITLE
Support filtering of resources

### ISSUE THREAD

**Issue by vontell** [phlask/phlask-map#450] opened 2024-06-18 23:42 UTC
Currently, how the frontend works in terms of loading and filtering data is:

- Make a Firebase API call to get all of the resources
- In the frontend, [we have a filter for the resource type](https://github.com/phlask/phlask-map/blob/develop/src/selectors/waterSelectors.js#L12)
- [Markers are loaded into the map](https://github.com/phlask/phlask-map/blob/develop/src/components/ReactGoogleMaps/ReactGoogleMaps.js#L316-L332)

There are two pieces that need to be fixed:
1. Need to reimplement the filtering logic in [this file](https://github.com/phlask/phlask-map/blob/develop/src/selectors/waterSelectors.js#L12) (we can then remove the other selector files)
2. (optional) It would be nice to stream in or filter/query the firebase DB for certain fields [rather than loading all resources at once](https://github.com/phlask/phlask-map/blob/c353af6ca3450603261b24841386b319c8730941/src/actions/actions.js#L35-L45).

Expected behavior: the filters in the desktop mode work

**Comment by gcardonag** [comment] 2024-09-04 00:08
@vontell , should this be closed since it was marked done on the Phlask Data board?

**Comment by gcardonag** [comment] 2024-09-10 19:59
Caught up with @vontell and confirmed this can be closed as completed ✅

**Closed as completed by gcardonag** 2024-09-10 19:59 UTC
Labels: Version 2
